### ISSUE TITLE
Get all members from a hostgroup

### ISSUE THREAD

**Issue by tferic** [pynag/pynag#252] opened 2018-06-11 13:10 UTC
Hi

I wasn't able to find any documentation on how to get all hosts (members) from a hostgroup.
I prefer to get the result by using the pynag CLI, but I could use Python calls as well.

This is what I tried:
`pynag list hostgroup_name host_name where hostgroup_name=hgr_websites_ssllabs
hostgroup_name       host_name
--------------------------------------------------------------------------------
hgr_websites_ssllabs null
hgr_websites_ssllabs null
----------2 objects matches search condition------------------------------------`

Obviously, I'm not getting any host names (hostgroup members).
What's the correct way of doing it?

This is the relevant excerpt from my nagios hostgroup definition:
`
define hostgroup{
        hostgroup_name  hgr_mygroup       ; The name of the hostgroup
        alias           hostgroup_mygroup ; Long name of the group
        members         host1.myorg.ort_EXT,host1.myorg.org_INT,host2.myorg.org,host-3.myorg.org,host4.myorg.org,host5.myorg.org,host6.myorg.org,host7.myorg.org,host8.myorg.org,host9.myorg.org,host10.myorg.org,host11.myorg.org,host12.myorg.org,host13.myorg.org,host14.myorg.org,host15.myorg.org,host16.myorg.org,host17.myorg.org,host18.myorg.org,host19.myorg.org,host20.myorg.org,host21.myorg.org,host22.myorg.org,host23.myorg.org,host24.myorg.org,host25.myorg.org,host26.myorg.org,host27.myorg.org,host28.myorg.org,host29.myorg.org,host30.myorg.org
}`

**Comment by palli** [comment] 2018-06-12 00:47
This is by design. The command line only shows what is explicitly configured in the fields you ask for. So "pynag list members where hostgroup_name=hgr_mygroup" would print a comma separated list of those hosts. The cli will also not do any sort of implicit memberships (for example where the host definition had a hostgroups=hgr_mygroup".

The term pynag uses for this kind of "deep resolution" of memberships is "effective_hosts".

A python script like this should do what you need:
```
from pynag.Model import Hostgroup
my_group = Hostgroup.objects.get_by_shortname('hgr_mygroup')
for host in my_group.get_effective_hosts():
  print host.host_name
```

**Comment by palli** [comment] 2018-06-12 00:47
Marking as closed for now since everything is working as intended from pynag perspective, but feel free to re-open if I missed anything.

**Comment by palli** [comment] 2018-06-12 00:48
Marking as closed for now since everything is working as intended from pynag perspective, but feel free to re-open if I missed anything.

**Closed by palli** 2018-06-12 00:47 UTC

**Comment by tferic** [comment] 2018-06-12 07:17
Thanks palli, your answer is very helpful, I can now use it.

Two comments:
1. The CLI returns two objects, the first one being "null" and the second my desired list of hosts. I believe that the "null" object probably should not be there.
2. Your answer is so useful, that it may be really nice for others to find it in the documentation or examples.

Thanks a lot! :-)
